name: Trigger the Blog Build process

on:
  push:
    branches:
      - main

jobs:
  notify_blog:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Blog Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.BLOG }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/SuryaVenkatesan-Git/blog/dispatches \
            -d '{"event_type": "Changes-in-Content"}'
